packages:
  - packages/*

catalogMode: strict

catalogs:
  dev:
    '@antfu/eslint-config': ^6.2.0
    eslint: ^9.39.1
    husky: ^9.1.7
    lint-staged: ^16.2.7
    tsdown: ^0.16.6
    typescript: ^5.9.3

cleanupUnusedCatalogs: true
